# docker-compose.yml

services:
  comfyui:
    image: beat2319/comfyui:latest
    
    restart: unless-stopped
    
    ports:
      - "8188:8188"
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
    volumes:
      - ./models:/app/ComfyUI/models
      - ./input:/app/ComfyUI/input
      - ./output:/app/ComfyUI/output
      - ./custom-nodes:/app/ComfyUI/custom_nodes
      - ./user:/app/ComfyUI/user