# docker-compose.yml

version: '3.8'

services:
  comfyui:
    image: beat2319/comfyui:latest
    
    restart: unless-stopped
    
    ports:
      - "8188:8188"
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
    volumes:
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
      - ./custom_nodes:/app/custom_nodes